[project]
name = "autogen-dojo"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "autogen-agentchat>=0.5.5",
    "autogen-ext[azure,ollama,openai]>=0.5.5",
    "ipython>=9.2.0",
]
